Custom Entity Models manifest
ReviversMC/modget-manifests pull request #46
Opened 2022-01-02 00:59 UTC by TacoMonkey11

Just want to keep to the "One manifest per PR" rule

2022-01-02 01:38 UTC, TacoMonkey11 commented
WELL CRAP

2022-01-02 01:38 UTC, TacoMonkey11 commented
guess who forgot to make a new branch for the next manifest!

2022-01-06 08:20 UTC, thefirethirteen commented
Oh dang

2022-01-06 08:35 UTC, thefirethirteen requested changes
Looks good, but needs a little work.

2022-01-06 08:35 UTC, thefirethirteen commented on manifests/D/dorianpb/cem/main.yaml
> +publisher: Digifox03
Wrong publisher!

2022-01-06 08:35 UTC, thefirethirteen commented on manifests/E/emmaffle/quilt-loading-screen/1.x/1.3.x/1.3.x.yaml
> +# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json
Commenting here because I can't comment on the name

Wrong filename!

2022-01-06 08:35 UTC, thefirethirteen commented on manifests/E/emmaffle/quilt-loading-screen/1.x/1.3.x/1.3.x.yaml
> +# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json
I think it should be `1.3.0.yaml`

2022-01-06 08:35 UTC, thefirethirteen commented on lookup-table.yaml
> +    - packageId: Emmaffle.quilt-loading-screen
Either this packageId is wrong, or the folder `/manifests/E/emaffle` you made is wrong

2022-01-06 16:45 UTC, thefirethirteen requested changes
One last thing...

2022-01-06 16:45 UTC, thefirethirteen commented on lookup-table.yaml
> +    - packageId: Emmaffle.quilt-loading-screen
The folder still seems to be `emaffle`, and this is still `Emaffle`. Which one is it?

2022-01-08 14:46 UTC, thefirethirteen requested changes

2022-01-08 14:46 UTC, thefirethirteen commented on lookup-table.yaml
> +    - packageId: Emmaffle.quilt-loading-screen
The folder is `Emmafle`(one `f`)  while this is `Emmaffle` (double `f`). Which one is it?

2022-01-08 15:17 UTC, thefirethirteen approved these changes
Everything looks good now

2022-01-08 15:17 UTC, merged